<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Theme;
use App\Models\StudyLevel;
use App\Models\Subject;
use App\Models\LearningProgram;
use App\Models\SubjectStudyLevel;
use App\Models\ThemeLearningProgram;

class TopicFactory extends Factory
{
    private $values = [
        //Thema Mulțimea numerelor naturale
        [ "nume" => 'Mulţimi.Operaţii cu mulţimi. Mulţimile: N,Z,Q,R', "path" => '/multimi-operatii-cu-multimi' ],
        [ "nume" => 'Operaţii cu numere naturale', "path" => '/operatii-cu-numere-naturale' ],
        [ "nume" => 'Divizibilitate în N. Criteriile de divizibilitate cu 2, 3, 5, 9, 10', "path" => '/divizibilitate-in-n' ],
        [ "nume" => 'Cel mai mare divizor comun al două numere naturale', "path" => '/cel-mai-mare-divizor-comun' ],
        [ "nume" => 'Cel mai mic multiplu comun al două numere naturale', "path" => '/cel-mai-mic-multiplu-comun' ],
        [ "nume" => 'Modulul numărului întreg', "path" => '/modulul-numarului-intreg' ],
        [ "nume" => 'Operaţii cu numere întregi', "path" => '/operatii-cu-numere-intregi' ],
        [ "nume" => 'Scrierea numerelor raţionale în diverse forme', "path" => '/scrierea-numerelor-rationale' ],
        [ "nume" => 'Operaţii cu numere raţionale', "path" => '/operatii-cu-numere-rationale' ],
        [ "nume" => 'Rădăcina pătrată (radical), proprietăți', "path" => '/radacina-patrata' ],
        [ "nume" => 'Introducerea factorilor sub radical, scoaterea factorilor de sub radical', "path" => '/introducerea-factorilor-sub-radical' ],
        [ "nume" => 'Compararea unor numere ce conțin radicali. Modulul numărului real', "path" => '/compararea-numerelor-cu-radicali' ],
        [ "nume" => 'Operații cu radicali. Raţionalizarea numitorului', "path" => '/operatii-cu-radicali' ],
        [ "nume" => 'Submulţimi ale mulţimii numerelor reale. Noţiune de număr iraţional', "path" => '/submultimi-numere-reale' ],
        [ "nume" => 'Proporții', "path" => '/proportii' ],
        [ "nume" => 'Proprietatea fundamentală a proporției. Aflarea unui termen necunoscut al proporției', "path" => '/proprietatea-fundamentala-a-proportiei' ],
        [ "nume" => 'Mărimi direct proporționale', "path" => '/marimi-direct-proporționale' ],
        [ "nume" => 'Mărimi invers proporționale', "path" => '/marimi-invers-proporționale' ],
        [ "nume" => 'Regula de trei simplă', "path" => '/regula-de-trei-simpla' ],
        [ "nume" => 'Aflarea raportului procentual', "path" => '/aflarea-raportului-procentual' ],
        [ "nume" => 'Aflarea procentului dintr-un număr dat', "path" => '/aflarea-procentului-dintr-un-numar' ],
        [ "nume" => 'Aflarea unui număr când se cunoaște procentul din el', "path" => '/aflarea-numarului-cand-se-cunoaste-procentul' ],
        [ "nume" => 'Media aritmetică', "path" => '/media-aritmetica' ],
        [ "nume" => 'Expresii algebrice', "path" => '/expresii-algebrice' ],
        [ "nume" => 'Adunarea, scăderea numerelor reale reprezentate prin litere', "path" => '/adunarea-scaderea-numerelor-reale' ],
        [ "nume" => 'Înmulțirea numerelor reale reprezentate prin litere', "path" => '/inmultirea-numerelor-reale' ],
        [ "nume" => 'Împărțirea numerelor reale reprezentate prin litere', "path" => '/impartirea-numerelor-reale' ],
        [ "nume" => 'Ridicare la putere cu exponent natural un număr real reprezentat prin litere', "path" => '/ridicare-la-putere-cu-exponent-natural' ],
        [ "nume" => 'Formule de calcul prescurtat', "path" => '/formule-de-calcul-prescurtat' ],
        [ "nume" => 'Metoda factorului comun', "path" => '/metoda-factorului-comun' ],
        [ "nume" => 'Aplicarea formulelor de calcul prescurtat', "path" => '/aplicarea-formulelor-de-calcul-prescurtat' ],
        [ "nume" => 'Metoda grupării termenilor și scoaterii factorului comun', "path" => '/metoda-gruparii-scoaterii-factorului-comun' ],
        [ "nume" => 'Definiții', "path" => '/definitii' ],
        [ "nume" => 'Modalităţi de demonstraţie a identităţilor', "path" => '/modalitati-demonstratie-identitati' ],
        [ "nume" => 'Domeniul valorilor admisibile (DVA) al unei fracţii algebrice.', "path" => '/domeniul-valorilor-admisibile' ],
        [ "nume" => 'Operaţii aritmetice cu fracţii algebrice', "path" => '/operatii-cu-fractii-algebrice' ],
        [ "nume" => 'Sistemul cartezian de coordonate în plan. Axe', "path" => '/sistemul-cartezian-de-coordonate' ],
        [ "nume" => 'Originea sistemului, cadrane, abscisă, ordonată', "path" => '/originea-sistemului-cadrane-abscisa-ordonata' ],
        [ "nume" => 'Coordonatele punctului', "path" => '/coordonatele-punctului' ],
        [ "nume" => 'Domeniul de definiție, codomeniu', "path" => '/domeniul-de-definire' ],
        [ "nume" => 'Moduri de definire a funcției', "path" => '/moduri-de-definire-a-functiei' ],
        [ "nume" => 'Graficul funcției', "path" => '/graficul-functiei' ],
        [ "nume" => 'Funcția constantă. Reprezentarea grafică. Proprietăți', "path" => '/functia-constantareprezentare-grafica' ],
        [ "nume" => 'Proporţionalitate inversă', "path" => '/proportionalitate-inversa' ],
        [ "nume" => 'Funcția radical', "path" => '/functia-radical' ],
        [ "nume" => 'Cazuri particulare ale funcției de gradul II', "path" => '/cazuri-particulare-functia-gradul-ii' ],
        [ "nume" => 'Graficul funcției de gradul II.', "path" => '/graficul-functiei-gradul-ii' ],
        [ "nume" => 'Proprietățile funcției de gradul II', "path" => '/proprietatile-functiei-gradul-ii' ],
        [ "nume" => 'Noțiunea de ecuație cu o necunoscută', "path" => '/noțiunea-de-ecuatie-cu-o-necunoscuta' ],
        [ "nume" => 'Ecuații de gradul I cu o necunoscută', "path" => '/ecuatii-de-gradul-I-cu-o-necunoscuta' ],
        [ "nume" => 'Ecuații reductibile la ecuația de gradul I cu o necunoscută', "path" => '/ecuatii-reductibile-la-ecuatia-de-gradul-I' ],
        [ "nume" => 'Ecuații cu două necunoscute.Soluția. DVA', "path" => '/ecuatii-cu-doua-necunoscute' ],
        [ "nume" => 'Ecuații de gradul I cu două necunoscute', "path" => '/ecuatii-de-gradul-I-cu-doua-necunoscute' ],
        [ "nume" => 'Noțiune de sistem de 2 ecuații cu 2 necunoscute', "path" => '/noțiune-de-sistem-de-ecuatii-cu-doua-necunoscute' ],
        [ "nume" => 'Sisteme de 2 ecuații de gradul I cu 2 necunoscute', "path" => '/sisteme-de-ecuatii-cu-doua-necunoscute' ],
        [ "nume" => 'Metode de rezolvare a sistemelor de 2 ecuații de gradul I cu 2 necunoscute', "path" => '/metode-de-rezolvare-a-sistemelor-de-ecuatii-cu-doua-necunoscute' ],
        [ "nume" => 'Inegalități numerice.', "path" => '/inegalitati-numerice' ],
        [ "nume" => 'Intervale de numere reale. Operații cu intervale de numere reale', "path" => '/intervale-de-numere-reale' ],
        [ "nume" => 'Noțiunea de inecuație cu o necunoscută', "path" => '/noțiunea-de-inequatie-cu-o-necunoscuta' ],
        [ "nume" => 'Inecuații de gradul I cu 1 necunoscută', "path" => '/inequatiile-de-gradul-I' ],
        [ "nume" => 'Sisteme de inecuații de gradul I cu 1 necunoscută', "path" => '/sisteme-de-inequatiile-de-gradul-I' ],
        [ "nume" => 'Formula de rezolvare', "path" => '/formula-de-rezolvare' ],
        [ "nume" => 'Relații între soluții și coeficienți. Reciproca teoremei lui Viète', "path" => '/relatii-intre-solutii-si-coeficienti' ],
        [ "nume" => 'Ecuații reductibile la ecuația de gradul II cu o necunoscută', "path" => '/ecuatii-reductibile-la-ecuatia-de-gradul-II' ],
        [ "nume" => 'Inecuații de gradul II cu o necunoscută', "path" => '/inequatiile-de-gradul-II' ],
        [ "nume" => 'Metoda intervalelor', "path" => '/metoda-intervalelor' ],
        [ "nume" => 'Ecuații raționale', "path" => '/ecuatii-rationale' ],
        [ "nume" => 'Unități de măsură pentru lungime', "path" => '/unitati-de-masura-pentru-lungime' ],
        [ "nume" => 'Unități de măsură pentru suprafață', "path" => '/unitati-de-masura-pentru-suprafata' ],
        [ "nume" => 'Unități de măsură pentru volum', "path" => '/unitati-de-masura-pentru-volum' ],
        [ "nume" => 'Unități de măsură pentru capacitate', "path" => '/unitati-de-masura-pentru-capacitate' ],
        [ "nume" => 'Unități de măsură pentru masă', "path" => '/unitati-de-masura-pentru-masa' ],
        [ "nume" => 'Unități de măsură pentru timp', "path" => '/unitati-de-masura-pentru-timp' ],
        [ "nume" => 'Punct, dreaptă, plan, distanța dintre două puncte, măsura unghiului', "path" => '/punct-dreapta-plan' ],
        [ "nume" => 'Puncte coliniare. Semidreaptă. Segment.', "path" => '/puncte-coliniare-semidreapta-segment' ],
        [ "nume" => 'Unghi. Definiție, clasificare. Măsura unghiului', "path" => '/unghi-definitie-clasificare' ],
        [ "nume" => 'Poziţii relative a două drepte. Drepte paralele, perpendiculare', "path" => '/pozitii-relative-doua-drepte' ],
        [ "nume" => 'Simetria față de un punct, simetria față de o dreaptă', "path" => '/simetria-fata-de-un-punct-simetria-fata-de-o-dreapta' ],
        [ "nume" => 'Triunghi. Definiție, elemente, clasificarea triunghiurilor', "path" => '/triunghi-definitie-elemente-clasificarea-triunghiurilor' ],
        [ "nume" => 'Triunghiuri congruente. Criteriile de congruență', "path" => '/triunghiuri-congruente-criteriile-de-congruenta' ],
        [ "nume" => 'Triunghiuri asemenea. Teorema lui Thales', "path" => '/triunghiuri-asemenea-teorema-lui-thales' ],
        [ "nume" => 'Linii importante în triunghi => mediana, bisectoarea, înălțimea, mediatoarea', "path" => '/linii-importante-in-triunghi-mediana-bisectoarea-inaltimea-mediatoarea' ],
        [ "nume" => 'Suma măsurilor unghiurilor unui triunghi. Teorema unghiului exterior', "path" => '/suma-masurilor-unghiurilor-unui-triunghi-teorema-unghiului-exterior' ],
        [ "nume" => 'Proprietățile triunghiului isoscel', "path" => '/proprietati-triunghi-isoscel' ],
        [ "nume" => 'Proprietățile triunghiului echilateral', "path" => '/proprietati-triunghi-echilateral' ],
        [ "nume" => 'Proprietățile triunghiului dreptunghic', "path" => '/proprietati-triunghi-dreptunghic' ],
        [ "nume" => 'Teorema înălțimii. Teorema catetei. Teorema lui Pitagora', "path" => '/teorema-inaltimii-teorema-catetei-teorema-lui-pitagora' ],
        [ "nume" => 'Noțiunea de poligon. Poligoane convexe. Elemente', "path" => '/notiunea-de-poligon-poligoane-convexe-elemente' ],
        [ "nume" => 'Noțiunea de patrulater. Elemente. Patrulatere convexe', "path" => '/notiunea-de-patrulater-elemente-patrulatere-convexe' ],
        [ "nume" => 'Paralelogramul. Elemente, proprietăți, criterii', "path" => '/paralelogramul-elemente-proprietati-criterii' ],
        [ "nume" => 'Dreptunghiul, elemente, proprietăți, criterii', "path" => '/dreptunghiul-elemente-proprietati-criterii' ],
        [ "nume" => 'Rombul, elemente, proprietăți, criterii', "path" => '/rombul-elemente-proprietati-criterii' ],
        [ "nume" => 'Pătratul, elemente, proprietăți, criterii', "path" => '/patratul-elemente-proprietati-criterii' ],
        [ "nume" => 'Trapezul, elemente, clasificare, proprietăți. Linia mijlocie a trapezului', "path" => '/trapezul-elemente-clasificare-proprietati-linia-mijlocie-a-trapezului' ],
        [ "nume" => 'Noțiunea de poligon regulat. Elemente. Triunghiul echilateral, pătratul', "path" => '/notiunea-de-poligon-regulat-elemente-triunghiul-echilateral-patratul' ],
        [ "nume" => 'Cercul. Discul. Elemente', "path" => '/cercul-discul-elemente' ],
        [ "nume" => 'Poziția relativă a unei drepte față de un cerc', "path" => '/pozitia-relativa-a-unei-drepte-fata-de-un-cerc' ],
        [ "nume" => 'Unghi la centru. Unghi înscris în cerc. Arc de cerc', "path" => '/unghi-la-centru-unghi-inscris-in-cerc-arc-de-cerc' ],
        [ "nume" => 'Tangenta la cerc. Proprietăți', "path" => '/tangenta-la-cerc-proprietati' ],
        [ "nume" => 'Proprietatea coardelor egal depărtate de centrul cercului', "path" => '/proprietatea-coardelor-egal-departate-de-centrul-cercului' ],
        [ "nume" => 'Noțiune de arie', "path" => '/notiune-de-arie' ],
        [ "nume" => 'Aria pătratului, dreptunghiului', "path" => '/aria-patrului-dreptunghiului' ],
        [ "nume" => 'Aria paralelogramului', "path" => '/aria-paralelogramului' ],
        [ "nume" => 'Aria rombului', "path" => '/aria-rombului' ],
        [ "nume" => 'Aria triunghiului (A = 0,5 ah; formula lui Heron)', "path" => '/aria-triunghiului-formula-lui-heron' ],
        [ "nume" => 'Aria trapezului', "path" => '/aria-trapezului' ],
        [ "nume" => 'Aria triunghiului echilateral', "path" => '/aria-triunghiului-echilateral' ],
        [ "nume" => 'Lungimea cercului. Aria discului', "path" => '/lungimea-cercului-aria-discului' ],
        [ "nume" => 'Prisma și elementele ei, clasificarea prismelor', "path" => '/prisma-elemente-clasificarea-prismelor' ],
        [ "nume" => 'Aria suprafețelor și volumul prismei drepte', "path" => '/aria-suprafetelor-si-volumul-prismei-drepte' ],
        [ "nume" => 'Piramida și elementele ei, clasificarea piramidelor', "path" => '/piramida-elemente-clasificarea-piramidelor' ],
        [ "nume" => 'Aria suprafețelor și volumul piramidei regulate (triunghiulare, patrulatere)', "path" => '/aria-suprafetelor-si-volumul-piramidei-regulate' ],
        [ "nume" => 'Noțiune de cilindru. Cilindrul circular drept și elementele lui', "path" => '/notiune-de-cilindru-cilindrul-circular-drept-elemente' ],
        [ "nume" => 'Aria suprafețelor și volumul cilindrului circular drept', "path" => '/aria-suprafetelor-si-volumul-cilindrului-circular-drept' ],
        [ "nume" => 'Noțiune de con. Conul circular drept și elementele lui', "path" => '/notiune-de-con-conul-circular-drept-elemente' ],
        [ "nume" => 'Aria suprafețelor și volumul conului circular drept', "path" => '/aria-suprafetelor-si-volumul-conului-circular-drept' ],
        [ "nume" => 'Sfera și corpul sferic. Elemente', "path" => '/sfera-corpul-sferic-elemente' ],
        [ "nume" => 'Aria suprafeței sferice. Volumul corpului sferic', "path" => '/aria-suprafetei-sferice-volumul-corpului-sferic' ],
      

        // Thema România în Primul Război Mondial
        [ "nume" => 'Opțiunile politice în perioada neutralității', "path" => '/optiunile-politice-in-perioada-neutralitatii' ],
        [ "nume" => 'Intrarea României în război', "path" => '/intrarea-romaniei-in-razboi' ],
        [ "nume" => 'Operațiile militare din anul 1917', "path" => '/operatiile-militare-din-anul-1917' ],
        [ "nume" => 'Agravarea situației pe frontul român', "path" => '/agravarea-situatiei-pe-frontul-roman' ],
        [ "nume" => 'Armistițiul de la Focșani și Pacea de la București', "path" => '/armistitiul-de-la-focsani-si-pacea-de-la-bucuresti' ],
        [ "nume" => 'Mișcarea națională a românilor din Basarabia până în octombrie 1917', "path" => '/miscarea-nationala-a-romanilor-din-basarabia' ],
        [ "nume" => 'Republica Democratică Moldovenească', "path" => '/republica-democratica-moldoveneasca' ],
        [ "nume" => 'Mișcarea națională a românilor din stânga Nistrului', "path" => '/miscarea-nationala-a-romanilor-din-stanga-nistrului' ],
        [ "nume" => 'Unirea Basarabiei cu România', "path" => '/unirea-basarabiei-cu-romania' ],
        [ "nume" => 'Unirea Bucovinei cu România', "path" => '/unirea-bucovinei-cu-romania' ],
        [ "nume" => 'Unirea Transilvaniei cu România', "path" => '/unirea-transilvaniei-cu-romania' ],
        [ "nume" => 'Recunoașterea internațională a Marii Uniri', "path" => '/recunoasterea-internationala-a-marii-uniri' ],
        [ "nume" => 'Conferința de Pace de la Paris (18 ianuarie 1919 - 21 ianuarie 1920)', "path" => '/conferinta-de-pace-de-la-paris' ],
        [ "nume" => 'Sistemul Versailles-Washington', "path" => '/sistemul-versailles-washington' ],
        [ "nume" => 'Noua ordine internațională', "path" => '/noua-ordine-internationala' ],
        [ "nume" => 'Conferința de la Washington', "path" => '/conferinta-de-la-washington' ],
        [ "nume" => 'Viața politică în SUA', "path" => '/viata-politica-in-sua' ],
        [ "nume" => 'Dezvoltarea economico-socială în SUA', "path" => '/dezvoltarea-economica-sociala-in-sua' ],
        [ "nume" => 'Depășirea crizei. New Deal (Noul Curs)', "path" => '/depasirea-crizei-new-deal-noul-curs' ],
        [ "nume" => 'Politica externă a SUA', "path" => '/politica-externa-a-sua' ],
        [ "nume" => 'Viața politică în Marea Britanie', "path" => '/viata-politica-in-marea-britanie' ],
        [ "nume" => 'Viața social-economică în Marea Britanie', "path" => '/viata-social-economica-in-marea-britanie' ],
        [ "nume" => 'Politica Externă a Marii Britanii', "path" => '/politica-externa-a-marii-britanii' ],
        [ "nume" => 'Viața politică în Franța', "path" => '/viata-politica-in-franta' ],
        [ "nume" => 'Viața economică în Franța', "path" => '/viata-economica-in-franta' ],
        [ "nume" => 'Politica externă a Franței', "path" => '/politica-externa-a-frantei' ],
        [ "nume" => 'Republica de la Weimar', "path" => '/republica-de-la-weimar' ],
        [ "nume" => 'Viața social-economică (1918-1932) în Germania', "path" => '/viata-social-economica-1918-1932-in-germania' ],
        [ "nume" => 'Politica internă a Germaniei. Ascensiunea nazismului', "path" => '/politica-interna-a-germaniei-ascensiunea-nazismului' ],
        [ "nume" => 'Politica externă a Germaniei', "path" => '/politica-externa-a-germaniei' ],
        [ "nume" => 'Ascensiunea fascismului în Italia', "path" => '/ascensiunea-fascismului-in-italia' ],
        [ "nume" => 'Situația economică și socială în Italia', "path" => '/situația-economica-și-sociala-în-italia' ],
        [ "nume" => 'Politica externă a Italiei', "path" => '/politica-externa-a-italiei' ],
        [ "nume" => 'Viața politică în Spania', "path" => '/viata-politica-in-spania' ],
        [ "nume" => 'Războiul Civil din Spania (1936-1939)', "path" => '/razboiul-civil-din-spania-1936-1939' ],
        [ "nume" => 'Viața politică internă a României (1918-1938)', "path" => '/viata-politica-interna-a-romaniei-1918-1938' ],
        [ "nume" => 'Regimul de autoritate monarhică (1938-1940)', "path" => '/regimul-de-autoritate-monarhica-1938-1940' ],
        [ "nume" => 'Evoluția demografică și social-economică a României', "path" => '/evolutia-demografica-si-social-economica-a-romaniei' ],
        [ "nume" => 'Politica externă a României', "path" => '/politica-externa-a-romaniei' ],
        [ "nume" => 'Participarea basarabenilor în viața politică a României', "path" => '/participarea-basarabenilor-in-viata-politica-Romaniei' ],
        [ "nume" => 'Viața social-economică în Basarabia', "path" => '/viata-social-economica-in-basarabia' ],
        [ "nume" => 'Formarea RASSM', "path" => '/formarea-rassm' ],
        [ "nume" => 'Evoluția social-economică în RASSM', "path" => '/evolutia-social-economica-in-rassm' ],
        [ "nume" => 'Politica cultural-lingvistică în RASSM', "path" => '/politica-cultural-lingvistica-in-rassm' ],
        [ "nume" => 'Marea Epurare din anii 30', "path" => '/marea-epurare-din-anii-30' ],
        [ "nume" => 'Știința și tehnica în perioada interbelică', "path" => '/stiinta-si-tehnica-in-perioada-interbelica' ],
        [ "nume" => 'Literatură în perioada interbelică', "path" => '/literatura-in-perioada-interbelica' ],
        [ "nume" => 'Arta în perioada interbelică', "path" => '/arta-in-perioada-interbelica' ],
        [ "nume" => 'Arhitectura în perioada interbelică', "path" => '/arhitectura-in-perioada-interbelica' ],
        [ "nume" => 'Cinematografia în perioada interbelică', "path" => '/cinematografia-in-perioada-interbelica' ],
        [ "nume" => 'Sportul în perioada interbelică', "path" => '/sportul-in-perioada-interbelica' ],
        [ "nume" => 'Învățământul în România interbelică', "path" => '/invatamantul-in-romania-interbelica' ],
        [ "nume" => 'Știința și tehnica în România interbelică', "path" => '/stiinta-si-tehnica-in-romania-interbelica' ],
        [ "nume" => 'Literatura românească interbelică', "path" => '/literatura-romaneasca-interbelica' ],
        [ "nume" => 'Presa românească interbelică', "path" => '/presa-romaneasca-interbelica' ],
        [ "nume" => 'Artele în România interbelică', "path" => '/artele-in-romania-interbelica' ],
        [ "nume" => 'Muzica românească interbelică', "path" => '/muzica-romaneasca-interbelica' ],
        [ "nume" => 'Radioul, teatrul și cinematografia în România interbelică', "path" => '/radioul-teatrul-si-cinematografia-in-romania-interbelica' ],
        [ "nume" => 'Biserica în România interbelică', "path" => '/biserica-in-romania-interbelica' ],
        [ "nume" => 'Cultura în Basarabia', "path" => '/cultura-in-basarabia' ],
        [ "nume" => 'Crearea sistemului de securitate colectivă', "path" => '/crearea-sistemului-de-securitate-colectiva' ],
        [ "nume" => 'Calea spre război - eșecul securității colective', "path" => '/calea-spre-razboi-esecul-securitatii-colective' ],
        [ "nume" => 'Declanșarea confruntării diplomatice', "path" => '/declansarea-confruntarii-diplomatice' ],
        [ "nume" => 'Relațiile cu URSS (1922-1933)', "path" => '/relatiile-cu-urss-1922-1933' ],
        [ "nume" => 'Ameliorarea relațiilor româno-sovietice', "path" => '/ameliorarea-relatiilor-romano-sovietice' ],
        [ "nume" => 'Semnarea Pactului de neagresiune sovieto-german', "path" => '/semnarea-pactului-de-neagresiune-sovieto-german' ],
        [ "nume" => 'Consecințele Pactului Ribbentrop-Molotov', "path" => '/consecintele-pactului-ribbentrop-molotov' ],
        [ "nume" => 'Anexarea Basarabiei de către URSS', "path" => '/anexarea-basarabiei-de-catre-urss' ],
        [ "nume" => 'Dictatul de la Viena', "path" => '/dictatul-de-la-viena' ],
        [ "nume" => 'Cedarea Cadrilaterului', "path" => '/cedarea-cadrilaterului' ],
        [ "nume" => 'Constituirea Republicii Sovietice Socialiste Moldovenești (RSSM)', "path" => '/constituirea-republicii-sovietice-socialiste-moldovenesti' ],
        [ "nume" => 'Politici social-economice în RSSM', "path" => '/politici-social-economice-in-rssm' ],
        [ "nume" => 'Politica în domeniul învățământului și culturii în RSSM', "path" => '/politica-in-domeniul-invatamantului-si-culturii-in-rssm' ],
        [ "nume" => 'Represiunile în RSSM', "path" => '/represiunile-in-rssm' ],
        [ "nume" => 'Declanșarea celui de-al Doilea Război Mondial', "path" => '/declansarea-celui-de-al-doilea-razboi-mondial' ],
        [ "nume" => 'Operațiile militare din Africa', "path" => '/operatiile-militare-din-africa' ],
        [ "nume" => 'Diplomația Germaniei în anii 1940-1941', "path" => '/diplomatia-germaniei-in-anii-1940-1941' ],
        [ "nume" => 'Operațiile militare din Balcani și Europa de Sud-Est', "path" => '/operatiile-militare-din-balcani-si-europa-de-sud-est' ],
        [ "nume" => 'Ofensiva germană în 1942 și contraofensiva sovietică și a Alianței antihitleriste', "path" => '/ofensiva-germana-contraofensiva-sovietica' ],
        [ "nume" => 'Ofensiva Coaliției antihitleriste', "path" => '/ofensiva-coalitiei-antihitleriste' ],
        [ "nume" => 'Înțelegerea Churchill-Stalin de împărțire a Europei', "path" => '/intelegerea-churchill-stalin-de-impartire-a-europei' ],
        [ "nume" => 'Sfârșitul războiului în Europa', "path" => '/sfarsitul-razboiului-in-europa' ],
        [ "nume" => 'Conferințele interaliate postbelice', "path" => '/conferintele-interaliate-postbelice' ],
        [ "nume" => 'Operațiile din Pacific și colapsul Japoniei. Sfârșitul Război II Mondial', "path" => '/sfarsitul-razboiului-mondial' ],
        [ "nume" => 'Statul Național-Legionar', "path" => '/statul-national-legionar' ],
        [ "nume" => 'Intrarea României în război', "path" => '/intrarea-romaniei-in-razboi' ],
        [ "nume" => 'Basarabia, Bucovina și Transnistria în anii 1941-1944', "path" => '/basarabia-bucovina-si-transnistria-in-anii-1941-1944' ],
        [ "nume" => '1941-1944: continuarea războiului în est', "path" => '/1941-1944-continuarea-razboiului-in-est' ],
        [ "nume" => 'Primăvara-vara 1944 => reocuparea Basarabiei de către URSS', "path" => '/1944-reocuparea-basarabiei-de-catre-urss' ],
        [ "nume" => 'Actul de la 23 august 1944', "path" => '/actul-de-la-23-august-1944' ],
        [ "nume" => 'Participarea României la războiul antihitlerist', "path" => '/participarea-romaniei-la-razboiul-antihitlerist' ],
        [ "nume" => 'Crimele de război ale Axei', "path" => '/crimele-de-razboi-ale-axei' ],
        [ "nume" => 'Holocaustul', "path" => '/holocaustul' ],
        [ "nume" => 'Specificul Holocaustului în 1938-1944 pe teritoriul Regatului României', "path" => '/holocaustului-in-1938-1944-in-romania' ],
        [ "nume" => 'Crimele de război ale membrilor Coaliției antihitleriste', "path" => '/crimele-de-razboi-ale-membrilor-coalitiei-antihitleriste' ],
        [ "nume" => 'Consecințele celui de-al Doilea Război Mondial', "path" => '/consecintele-celui-de-al-doilea-razboi-mondial' ],
        [ "nume" => 'Consecințele celui de-al Doilea Război Mondial pentru România și pentru Basarabia', "path" => '/consecinte-razboi-mondial-romania-basarabia' ],
        [ "nume" => 'Conferința de Pace de la Paris (29 iulie-15 octombrie 1946)', "path" => '/conferinta-de-pace-de-la-paris-29-iulie-15-octombrie-1946' ],
        [ "nume" => 'Confruntarea Est-Vest (1947-1962)', "path" => '/confruntarea-est-vest-1947-1962' ],
        [ "nume" => 'Destinderea relațiilor internaționale (1963-1979)', "path" => '/destinderea-relatiilor-internationale-1963-1979' ],
        [ "nume" => 'Anti-destindere (1979-1985)', "path" => '/anti-destindere-1979-1985' ],
        [ "nume" => 'Noua mentalitate politică', "path" => '/noua-mentalitate-politica' ],
        [ "nume" => 'Constituirea și activitatea Organizației Națiunilor Unite (ONU)', "path" => '/constituirea-si-activitatea-organizatiei-natiunilor-unite-onu' ],
        [ "nume" => 'Viața politică în URSS în perioada postbelică', "path" => '/viata-politica-in-urss-in-perioada-postbelica' ],
        [ "nume" => 'Dezintegrarea URSS', "path" => '/dezintegrarea-urss' ],
        [ "nume" => 'Evoluția economică în URSS în perioada postbelică', "path" => '/evolutia-economica-in-urss-in-perioada-postbelica' ],
        [ "nume" => 'Politica externă a URSS în perioada postbelică', "path" => '/politica-externa-a-urss-in-perioada-postbelica' ],
        [ "nume" => 'Viața politică în RSSM în perioada postbelică', "path" => '/viata-politica-in-rssm-in-perioada-postbelica' ],
        [ "nume" => 'Populația RSSM în perioada postbelică', "path" => '/populatia-rssm-in-perioada-postbelica' ],
        [ "nume" => 'Colectivizarea forțată', "path" => '/colectivizarea-fortata' ],
        [ "nume" => 'Economia în RSSM în perioada postbelică', "path" => '/economia-in-rssm-in-perioada-postbelica' ],
        [ "nume" => 'Foametea organizată din anii 1946-1947', "path" => '/foametea-organizata-din-anii-1946-1947' ],
        [ "nume" => 'Deportările din anul 1949 - Operația Sud', "path" => '/deportarile-din-anul-1949-operatia-sud' ],
        [ "nume" => 'Represiuni împotriva religiei și a bisericii', "path" => '/represiuni-impotriva-religiei-si-a-bisericii' ],
        [ "nume" => 'Operația Sever (Nord) (1951)', "path" => '/operatia-sever-nord-1951' ],
        [ "nume" => 'Mișcarea națională în RSSM între 1985-1991', "path" => '/miscarea-nationala-in-rssm-intre-1985-1991' ],
        [ "nume" => 'Mișcări separatiste', "path" => '/miscari-separatiste' ],
        [ "nume" => 'Calea spre declararea independenței', "path" => '/calea-spre-declararea-independentei' ],
        [ "nume" => 'Războiul de pe Nistru', "path" => '/razboiul-de-pe-nistru' ],
        [ "nume" => 'Reglementarea conflictului', "path" => '/reglementarea-conflictului' ],
        [ "nume" => 'Politica culturală în RSSM', "path" => '/politica-culturala-in-rssm' ],
        [ "nume" => 'Învățământul în RSSM', "path" => '/invatamantul-in-rssm' ],
        [ "nume" => 'Știința în RSSM', "path" => '/stiinta-in-rssm' ],
        [ "nume" => 'Literatura în RSSM', "path" => '/literatura-in-rssm' ],
        [ "nume" => 'Teatrul și cinematografia în RSSM', "path" => '/teatrul-si-cinematografia-in-rssm' ],
        [ "nume" => 'Muzica în RSSM', "path" => '/muzica-in-rssm' ],
        [ "nume" => 'Artele plastice în RSSM', "path" => '/artele-plastice-in-rssm' ],
        [ "nume" => 'Politica față de biserică în RSSM', "path" => '/politica-fata-de-biserica-in-rssm' ],
        [ "nume" => 'Literatura  în Republica Moldova', "path" => '/literatura-in-republica-moldova' ],
        [ "nume" => 'Teatrul în Republica Moldova', "path" => '/teatrul-in-republica-moldova' ],
        [ "nume" => 'Arta muzicală în Republica Moldova', "path" => '/arta-muzicala-in-republica-moldova' ],
        [ "nume" => 'Artele plastice în Republica Moldova', "path" => '/artele-plastice-in-republica-moldova' ],
        [ "nume" => 'Cinematografia în Republica Moldova', "path" => '/cinematografia-in-republica-moldova' ],
        [ "nume" => 'Învățământul în Republica Moldova', "path" => '/invatamantul-in-republica-moldova' ],
        [ "nume" => 'Știința în Republica Moldova', "path" => '/stiinta-in-republica-moldova' ],
        [ "nume" => 'Muzeele naționale și locale. Monumente de patrimoniu național', "path" => '/muzeele-nationale-si-locale' ],
        [ "nume" => 'Tehnologiile spațiale', "path" => '/tehnologiile-spatiale' ],
        [ "nume" => 'Dezvoltarea tehnologiilor informaționale', "path" => '/dezvoltarea-tehnologiilor-informationale' ],
        [ "nume" => 'Știința în Epoca Contemporană', "path" => '/stiinta-in-epoca-contemporana' ],
        [ "nume" => 'Literatura în Epoca Contemporană', "path" => '/literatura-in-epoca-contemporana' ],
        [ "nume" => 'Cultura de masă în Epoca Contemporană', "path" => '/cultura-de-masa-in-epoca-contemporana' ],
        [ "nume" => 'Artele în Epoca Contemporană', "path" => '/artele-in-epoca-contemporana' ],
        [ "nume" => 'Monumente de patrimoniu universal', "path" => '/monumente-de-patrimoniu-universal' ],
      

        //LIMBA ROMANA

        [ "nume" => 'Limba română - limba maternă', "path" => '/limba-romana-limba-materna' ],
        [ "nume" => 'Limba - mijloc de exprimare artistică', "path" => '/limba-mijloc-de-exprimare-artistica' ],
        [ "nume" => 'Limba română - limbă europeană', "path" => '/limba-romana-limba-europeana' ],
        [ "nume" => 'Limba română azi.', "path" => '/limba-romana-azi' ],
        [ "nume" => 'Evoluția limbii române. Caracterul ei latin', "path" => '/evolutia-limbii-romane-caracterul-ei-latin' ],
        [ "nume" => 'Patria, patriotism', "path" => '/patria-patriotism' ],
        [ "nume" => 'Personalitățile neamului', "path" => '/personalitatile-neamului' ],
        [ "nume" => 'Comunitatea vorbitorilor de limbă română', "path" => '/comunitatea-vorbitorilor-de-limba-romana' ],
        [ "nume" => 'Ziua Limbii Române', "path" => '/ziua-limbii-romane' ],
        [ "nume" => 'Cultura națională', "path" => '/cultura-nationala' ],
        [ "nume" => 'Cultura europeană și contacte culturale', "path" => '/cultura-europeana-si-contacte-culturale' ],
        [ "nume" => 'Elemente de fonetică şi ortografie', "path" => '/elemente-de-fonetica-si-ortografie' ],
        [ "nume" => 'Vocabularul limbii române', "path" => '/vocabularul-limbii-romane' ],
        [ "nume" => 'Structura vocabularului', "path" => '/structura-vocabularului' ],
        [ "nume" => 'Vocabularul fundamental și masa vocabularului', "path" => '/vocabularul-fundamental-si-masa-vocabularului' ],
        [ "nume" => 'Circulația cuvintelor în timp. Arhaismele. Neologismele', "path" => '/arhaismele-neologismele' ],
        [ "nume" => 'Cuvintele moștenite și cuvintele împrumutate', "path" => '/cuvintele-mostenite-si-cuvintele-imprumutate' ],
        [ "nume" => 'Sinonime. Seriile sinonimice', "path" => '/sinonime-seriile-sinonimice' ],
        [ "nume" => 'Antonime', "path" => '/antonime' ],
        [ "nume" => 'Câmpul lexical. ', "path" => '/campul-lexical' ],
        [ "nume" => 'Familia lexicală. Câmpul derivativ', "path" => '/familia-lexicala-campul-derivativ' ],
        [ "nume" => 'Omonime', "path" => '/omonime' ],
        [ "nume" => 'Tipuri de dicționare', "path" => '/tipuri-de-dictionare' ],
        [ "nume" => 'Mijloace interne de îmbogățire a vocabularului => derivarea, compunerea, conversiunea, abrevierea', "path" => '/mijloace-interne-de-imbogatire-a-vocabularului' ],
        [ "nume" => 'Mijloacele expresive ale limbii', "path" => '/mijloacele-expresive-ale-limbii' ],
        [ "nume" => 'Îmbinări libere de cuvinte, locuțiuni, expresii frazeologice', "path" => '/imbinari-libere-de-cuvinte-locutiuni-expresii-frazeologice' ],
        [ "nume" => 'Monosemia și polisemia', "path" => '/monosemia-si-polisemia' ],
        [ "nume" => 'Sensul propriu/figurat; fundamental/secundar; lexical/gramatical', "path" => '/sensul-propriu-figurat-fundamental-secundar-lexical-gramatical' ],
        [ "nume" => 'Limba literară/populară;  limba vorbită/scrisă', "path" => '/limba-literara-populara-limba-vorbita-scrisa' ],
        [ "nume" => 'Stilurile funcționale ale limbii', "path" => '/stilurile-functionale-ale-limbii' ],
        [ "nume" => 'Substantivul. Locuțiunea substantivală. Ortografia substantivului. Genul, numărul, cazul', "path" => '/substantivul-locutiunea-substantivala' ],
        [ "nume" => 'Articolul', "path" => '/articolul' ],
        [ "nume" => 'Adjectivul. Locuțiunea adjectivală. Ortografia adjectivului', "path" => '/adjectivul-locutiunea-adjectivala' ],
        [ "nume" => 'Verbul. Locuțiunea verbală. Ortografia verbului', "path" => '/verbul-locutiunea-verbal-ortografia-verbului' ],
        [ "nume" => 'Pronumele şi adjectivele pronominale. Ortografia pronumelui', "path" => '/pronumele-si-adjectivele-pronominale' ],
        [ "nume" => 'Numeralul. Ortografia numeralului', "path" => '/numeralul-ortografia-numeralului' ],
        [ "nume" => 'Adverbul. Locuțiunea adverbială. Ortografia adverbului', "path" => '/adverbul-locutiunea-adverbiala' ],
        [ "nume" => 'Prepoziția. Locuțiunea prepozițională', "path" => '/prepozitia-locutiunea-prepozitionala' ],
        [ "nume" => 'Conjuncția. Locuțiunea conjuncțională. Ortografia conjuncției', "path" => '/conjugntia-locutiunea-conjuctionala' ],
        [ "nume" => 'Interjecția', "path" => '/interjectia' ],
        [ "nume" => 'Propoziția. Clasificarea propozițiilor. Relații sintactice în propoziție', "path" => '/propozitia-clasificarea-propozitiilor' ],
        [ "nume" => 'Funcțiile sintactice', "path" => '/functiile-sintactice' ],
        [ "nume" => 'Cuvinte/construcții/propoziții incidente', "path" => '/cuvinte-constructii-propozitii-incidente' ],
        [ "nume" => 'Norme de punctuație în propoziție', "path" => '/norme-de-punctuatie-in-propozitie' ],
        [ "nume" => 'Fraza. Elementele de relație în frază', "path" => '/fraza-elementele-de-relatie-in-fraza' ],
        [ "nume" => 'Coordonarea și subordonarea în frază', "path" => '/coordonarea-si-subordonarea-in-fraza' ],
        [ "nume" => 'Subiectul. Propoziția subordonată subiectivă', "path" => '/subiectul-propozitia-subordonata-subiectiva' ],
        [ "nume" => 'Predicatul verbal. Predicatul nominal. Propoziția subordonată predicativă', "path" => '/predicatul-verbal-predicatul-nominal' ],
        [ "nume" => 'Atributul. Propoziția subordonată atributivă', "path" => '/atributul-propozitia-subordonata-atributiva' ],
        [ "nume" => 'Complementele necircumstanțiale => direct și indirect.', "path" => '/complementele-necircumstantiale-direct-si-indirect' ],
        [ "nume" => 'Propoziția subordonată completivă direct și indirectă', "path" => '/propozitia-subordonata-direct-si-indirecta' ],
        [ "nume" => 'Complementele circumstanțiale', "path" => '/complementele-circumstantiale' ],
        [ "nume" => 'Subordonatele circumstanțiale', "path" => '/subordonatele-circumstantiale' ],
        [ "nume" => 'Normele de punctuație în frază', "path" => '/normele-de-punctuatie-in-fraza' ],
        [ "nume" => 'Structura cărții', "path" => '/structura-cartii' ],
        [ "nume" => 'Cartea audio', "path" => '/cartea-audio' ],
        [ "nume" => 'Publicațiile periodice', "path" => '/publicatiile-periodice' ],
        [ "nume" => 'Tema, mesajul operei literare', "path" => '/tema-mesajul-operei-literare' ],
        [ "nume" => 'Motivul literar', "path" => '/motivul-literar' ],
        [ "nume" => 'Trăsături fizice și morale ale personajului', "path" => '/trasaturi-fizice-si-morale-ale-personajului' ],
        [ "nume" => 'Clasificarea personajelor', "path" => '/clasificarea-personajelor' ],
        [ "nume" => 'Caracterizarea personajului literar', "path" => '/caracterizarea-personajului-literar' ],
        [ "nume" => 'Personajul literar și personalitatea istorică', "path" => '/personajul-literar-si-personalitatea-istorica' ],
        [ "nume" => 'Text narativ => autor, narator, personaj, acțiune, cronotop', "path" => '/text-narativ' ],
        [ "nume" => 'Narațiune la persoana I și la persoana a III-a', "path" => '/naratziune-la-persoana-I-si-la-persoana-a-III-a' ],
        [ "nume" => 'Tema, idea principală/ ideile secundare ale textului narativ', "path" => '/tema-idea-principala-secundare' ],
        [ "nume" => 'Valorile textului epic', "path" => '/valorile-textului-epic' ],
        [ "nume" => 'Cronotopul (spatial și timpul)', "path" => '/cronotopul-spatial-si-timpul' ],
        [ "nume" => 'Moduri de expunere: narațiunea, dialogul, descrierea, monologul', "path" => '/moduri-de-expunere' ],
        [ "nume" => 'Momentele subiectului', "path" => '/momentele-subiectului' ],
        [ "nume" => 'Rezumatul textului epic', "path" => '/rezumatul-textului-epic' ],
        [ "nume" => 'Poezia lirică', "path" => '/poezia-lirica' ],
        [ "nume" => 'Eul liric', "path" => '/eul-liric' ],
        [ "nume" => 'Text dramatic', "path" => '/text-dramatic' ],
        [ "nume" => 'Elementele de versificație', "path" => '/elementele-de-versificatie' ],
        [ "nume" => 'Epitetul', "path" => '/epitetul' ],
        [ "nume" => 'Comparația', "path" => '/comparatia' ],
        [ "nume" => 'Personificarea', "path" => '/personificarea' ],
        [ "nume" => 'Enumerația', "path" => '/enumeratia' ],
        [ "nume" => 'Repetiția', "path" => '/repetitia' ],
        [ "nume" => 'Inversiunea', "path" => '/inversiunea' ],
        [ "nume" => 'Hiperbola', "path" => '/hiperbola' ],
        [ "nume" => 'Metafora', "path" => '/metafora' ],
        [ "nume" => 'Antiteza', "path" => '/antiteza' ],
        [ "nume" => 'Paralelismul sintactic', "path" => '/paralelismul-sintactic' ],
        [ "nume" => 'Exclamația retorică', "path" => '/exclamatia-retorica' ],
        [ "nume" => 'Interogația retorică', "path" => '/interogatia-retorica' ],
        [ "nume" => 'Invocația retorică', "path" => '/invocatia-retorica' ],
        [ "nume" => 'Alegoria', "path" => '/alegoria' ],
        [ "nume" => 'Anafora', "path" => '/anafora' ],
        [ "nume" => 'Ghicitoarea', "path" => '/ghicitoarea' ],
        [ "nume" => 'Proverbul', "path" => '/proverbul' ],
        [ "nume" => 'Aforismul', "path" => '/aforismul' ],
        [ "nume" => 'Zicătoarea', "path" => '/zicatoarea' ],
        [ "nume" => 'Frământarea de limbă', "path" => '/framantarea-de-limba' ],
        [ "nume" => 'Legenda', "path" => '/legenda' ],
        [ "nume" => 'Balada', "path" => '/balada' ],
        [ "nume" => 'Povestea', "path" => '/povestea' ],
        [ "nume" => 'Basmul popular și cult', "path" => '/basmul-popular-si-cult' ],
        [ "nume" => 'Snoava', "path" => '/snoava' ],
        [ "nume" => 'Parabola', "path" => '/parabola' ],
        [ "nume" => 'Schița', "path" => '/schita' ],
        [ "nume" => 'Povestirea', "path" => '/povestirea' ],
        [ "nume" => 'Nuvela', "path" => '/nuvela' ],
        [ "nume" => 'Romanul', "path" => '/romanul' ],
        [ "nume" => 'Fabula', "path" => '/fabula' ],
        [ "nume" => 'Pastelul', "path" => '/pastelul' ],
        [ "nume" => 'Doina', "path" => '/doina' ],
        [ "nume" => 'Imnul', "path" => '/imnul' ],
        [ "nume" => 'Oda', "path" => '/oda' ],
        [ "nume" => 'Poemul', "path" => '/poemul' ],
        [ "nume" => 'Comedia', "path" => '/comedia' ],
        [ "nume" => 'Literatura populară și literatura cultă', "path" => '/literatura-populara-si-literatura-culta' ],
        [ "nume" => 'Textul literar și nonliterar', "path" => '/textul-literar-si-nonliterar' ],
        [ "nume" => 'Textul argumentativ', "path" => '/textul-argumentativ' ],
        [ "nume" => 'Eseul cu tema: Patria/Limba română', "path" => '/eseul-cu-tema-patria-limba-romana' ],
        [ "nume" => 'Eseul cu tema: Familia / Şcoala', "path" => '/eseul-cu-tema-familia-scoala' ],
        [ "nume" => 'Eseul cu tema: Copilăria/Adolescenţa', "path" => '/eseul-cu-tema-copilaria-adolescenta' ],
        [ "nume" => 'Eseul cu tema: Universul/Natura', "path" => '/eseul-cu-tema-universul-natura' ],
        [ "nume" => 'Eseul cu tema: Dragostea / Prietenia', "path" => '/eseul-cu-tema-dragostea-prietenia' ],
        [ "nume" => 'Eseul cu tema: Timpul / Istoria', "path" => '/eseul-cu-tema-timpul-istoria' ],
        [ "nume" => 'Eseul cu tema: Călătorii / Lumi fantastice', "path" => '/eseul-cu-tema-calatorii-lumi-fantastice' ],
        [ "nume" => 'Eseul cu tema: Artistul / Ars poetica', "path" => '/eseul-cu-tema-artistul-ars-poetica' ],
        [ "nume" => 'Textul descriptiv', "path" => '/textul-descriptiv' ],
        [ "nume" => 'Descrierea de natură', "path" => '/descrierea-de-natura' ],
        [ "nume" => 'Descrierea de localitate', "path" => '/descrierea-de-localitate' ],
        [ "nume" => 'Descrierea de itinerar', "path" => '/descrierea-de-itinerar' ],
        [ "nume" => 'Descrierea de interior', "path" => '/descrierea-de-interior' ],
        [ "nume" => 'Descrierea de obiecte', "path" => '/descrierea-de-obiecte' ],
        [ "nume" => 'Descrierea de fiinţe', "path" => '/descrierea-de-fiinte' ],
        [ "nume" => 'Descrierea de activităţi', "path" => '/descrierea-de-activitati' ],
        [ "nume" => 'Portretul', "path" => '/portretul' ],
        [ "nume" => 'Textul narativ', "path" => '/textul-narativ' ],
        [ "nume" => 'Textul narativ-descriptiv', "path" => '/textul-narativ-descriptiv' ],
        [ "nume" => 'Textul cu dialog', "path" => '/textul-cu-dialog' ],
        [ "nume" => 'Textul explicative', "path" => '/textul-explicativ' ],
        [ "nume" => 'CV-ul', "path" => '/cv-ul' ],
        [ "nume" => 'Scrisoarea', "path" => '/scrisoarea' ],
        [ "nume" => 'Mesajul electronic', "path" => '/mesajul-electronic' ],
        [ "nume" => 'Notițele', "path" => '/notele' ],
        [ "nume" => 'Orarul activităților', "path" => '/orarul-activitatilor' ],
        [ "nume" => 'Instrucțiunea', "path" => '/instructiunea' ],
        [ "nume" => 'Rețeta', "path" => '/reteta' ],
        [ "nume" => 'Felicitarea electronică', "path" => '/felicitarea-electronica' ],
        [ "nume" => 'Anunțul', "path" => '/anuntul' ],
        [ "nume" => 'Completarea formularelor tipizate', "path" => '/completarea-formularelor-tipizate' ],
        [ "nume" => 'Forumul de discuții', "path" => '/forumul-de-discutii' ],
        [ "nume" => 'Invitația', "path" => '/invitatia' ],
        [ "nume" => 'Prezentarea experiențelor proprii de lectură', "path" => '/prezentarea-experientelor-de-lectura' ],
        [ "nume" => 'Verbalizarea reacției imediate / a stării postlectorale în raport cu un text literar', "path" => '/verbalizarea-reactiei-la-text-literar' ],
        [ "nume" => 'Raftul de literature artistică în biblioteca personală', "path" => '/raftul-de-literatura-artistica' ],
        [ "nume" => 'Literatura și artele', "path" => '/literatura-si-artele' ],
        [ "nume" => 'Literatura şi geografia', "path" => '/literatura-si-geografia' ],
        [ "nume" => 'Literatura și istoria', "path" => '/literatura-si-istoria' ],
        [ "nume" => 'Literatura și cunoașterea de sine', "path" => '/literatura-si-cunoasterea-de-sine' ],
        [ "nume" => 'Informațiile receptate din cotidian', "path" => '/informatiile-receptate-din-cotidian' ],
        [ "nume" => 'Discurs despre un eveniment sociocultural', "path" => '/discurs-despre-un-eveniment-sociocultural' ]
     
    ];
    private $index = 0;
    private $previousThemeId;
    private $orderNumber = 1;

    public function definition(): array
    {
        $thems = [ 
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor întregi', 			
             'Mulțimea numerelor întregi',  			
             'Mulțimea numerelor raționale',			
             'Mulțimea numerelor raționale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Rapoarte. Proporţii. Proprietatea fundamentală a proporţiilor',			
             'Rapoarte. Proporţii. Proprietatea fundamentală a proporţiilor',			
             'Mărimi direct proporţionale şi mărimi invers proporţionale. Regula de trei simplă',			
             'Mărimi direct proporţionale şi mărimi invers proporţionale. Regula de trei simplă',			
             'Mărimi direct proporţionale şi mărimi invers proporţionale. Regula de trei simplă',			
             'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',			
             'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',			
             'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',			
             'Media aritmetică',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Formule de calcul prescurtat',			
             'Metode de descompunere în factori',			
             'Metode de descompunere în factori',			
             'Metode de descompunere în factori',			
             'Transformări identice ale expresiilor algebrice',			
             'Transformări identice ale expresiilor algebrice',			
             'Rapoarte (fracții) algebrice, DVA',			
             'Rapoarte (fracții) algebrice, DVA',			
             'Coordonatele punctului pe plan',			
             'Coordonatele punctului pe plan',			
             'Coordonatele punctului pe plan',			
             'Noţiune de funcţie. Graficul funcţiei',			
             'Noţiune de funcţie. Graficul funcţiei',			
             'Noţiune de funcţie. Graficul funcţiei',			
             'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',			
             'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',			
             'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',			
             'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi', 			
             'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi', 			
             'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi', 			
             'Ecuaţii de gradul I cu o necunoscută',			
             'Ecuaţii de gradul I cu o necunoscută',			
             'Ecuaţii de gradul I cu o necunoscută',			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Sisteme de inecuaţii de gradul I cu o necunoscută',			
             'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',			
             'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',			
             'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',			
             'Inecuaţii de gradul II cu o necunoscută',			
             'Inecuaţii de gradul II cu o necunoscută',			
             'Ecuaţii raţionale cu o necunoscută',			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Poliedre',			
             'Poliedre',			
             'Poliedre',			
             'Poliedre',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
            'România în Primul Război Mondial',
            'România în Primul Război Mondial',
            'România în Primul Război Mondial',
            'România în Primul Război Mondial',
            'România în Primul Război Mondial',
            'Mișcarea națională a românilor din Basarabia și teritoriile din stânga Nistrului',
            'Mișcarea națională a românilor din Basarabia și teritoriile din stânga Nistrului',
            'Mișcarea națională a românilor din Basarabia și teritoriile din stânga Nistrului',
            'Formarea Statului Național Unitar Român. Recunoașterea Marii Uniri de la 1918',
            'Formarea Statului Național Unitar Român. Recunoașterea Marii Uniri de la 1918',
            'Formarea Statului Național Unitar Român. Recunoașterea Marii Uniri de la 1918',
            'Formarea Statului Național Unitar Român. Recunoașterea Marii Uniri de la 1918',
            'Conferinţa de Pace de la Paris. Sistemul de la Versailles',
            'Conferinţa de Pace de la Paris. Sistemul de la Versailles',
            'Conferinţa de Pace de la Paris. Sistemul de la Versailles',
            'Conferinţa de Pace de la Paris. Sistemul de la Versailles',
            'SUA în perioada interbelică',
            'SUA în perioada interbelică',
            'SUA în perioada interbelică',
            'SUA în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'Europa de Vest în perioada interbelică',
            'România în perioada interbelică',
            'România în perioada interbelică',
            'România în perioada interbelică',
            'România în perioada interbelică',
            'Basarabia în cadrul României Mari (1918-1940)',
            'Basarabia în cadrul României Mari (1918-1940)',
            'RASSM (1924-1940). Politica expansionistă a URSS',
            'RASSM (1924-1940). Politica expansionistă a URSS',
            'RASSM (1924-1940). Politica expansionistă a URSS',
            'RASSM (1924-1940). Politica expansionistă a URSS',
            'Cultura și știința în perioada interbelică',
            'Cultura și știința în perioada interbelică',
            'Cultura și știința în perioada interbelică',
            'Cultura și știința în perioada interbelică',
            'Cultura și știința în perioada interbelică',
            'Cultura și știința în perioada interbelică',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Cultura românească în 1918-40',
            'Alianțe și tratate politico-militare în perioada interbelică',
            'Alianțe și tratate politico-militare în perioada interbelică',
            'Relațiie sovieto-române(1918-1940). Pactul Molotov-Ribbentrop',
            'Relațiie sovieto-române(1918-1940). Pactul Molotov-Ribbentrop',
            'Relațiie sovieto-române(1918-1940). Pactul Molotov-Ribbentrop',
            'Relațiie sovieto-române(1918-1940). Pactul Molotov-Ribbentrop',
            'Relațiie sovieto-române(1918-1940). Pactul Molotov-Ribbentrop',
            'Pierderile teritoriale ale României în vara anului 1940',
            'Pierderile teritoriale ale României în vara anului 1940',
            'Pierderile teritoriale ale României în vara anului 1940',
            'Formarea RSSM și instaurarea regimului comunist',
            'Formarea RSSM și instaurarea regimului comunist',
            'Formarea RSSM și instaurarea regimului comunist',
            'Formarea RSSM și instaurarea regimului comunist',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Al Doilea Război Mondial 1939-1945',
            'Spațiul românesc între 1941 şi 1944', 
            'Spațiul românesc între 1941 şi 1944', 
            'Spațiul românesc între 1941 şi 1944', 
            'Spațiul românesc între 1941 şi 1944', 
            'Spațiul românesc între 1941 şi 1944', 
            'Spațiul românesc între 1941 şi 1944', 
            'Spațiul românesc între 1941 şi 1944', 
            'Crime de război. Holocaust', 
            'Crime de război. Holocaust', 
            'Crime de război. Holocaust', 
            'Crime de război. Holocaust', 
            'Consecințele celui de-al Doilea Război Mondial',
            'Consecințele celui de-al Doilea Război Mondial',  
            'Relațiile internaționale în perioada 1945-1991. Constituirea ONU', 
            'Relațiile internaționale în perioada 1945-1991. Constituirea ONU', 
            'Relațiile internaționale în perioada 1945-1991. Constituirea ONU', 
            'Relațiile internaționale în perioada 1945-1991. Constituirea ONU', 
            'Relațiile internaționale în perioada 1945-1991. Constituirea ONU', 
            'Relațiile internaționale în perioada 1945-1991. Constituirea ONU', 
            'Uniunea Sovietică în perioada postbelică',
            'Uniunea Sovietică în perioada postbelică',
            'Uniunea Sovietică în perioada postbelică',
            'Uniunea Sovietică în perioada postbelică',
            'RSSM. Economie şi societate (1944-1985)',
            'RSSM. Economie şi societate (1944-1985)',
            'RSSM. Economie şi societate (1944-1985)',
            'RSSM. Economie şi societate (1944-1985)',
            'Foametea, represiile și deportările staliniste din RSSM',
            'Foametea, represiile și deportările staliniste din RSSM',
            'Foametea, represiile și deportările staliniste din RSSM',
            'Foametea, represiile și deportările staliniste din RSSM',
            'RSSM între 1985-1991. Proclamarea independenței Republicii Moldova',
            'RSSM între 1985-1991. Proclamarea independenței Republicii Moldova',
            'RSSM între 1985-1991. Proclamarea independenței Republicii Moldova',
            'Războiul de pe Nistru',
            'Războiul de pe Nistru',
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Cultura și știința în RSSM (1944-1991)', 
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Evoluția culturii în Republica Moldova',
            'Cultura și știința universală în Epoca Contemporană',
            'Cultura și știința universală în Epoca Contemporană',
            'Cultura și știința universală în Epoca Contemporană',
            'Cultura și știința universală în Epoca Contemporană',
            'Cultura și știința universală în Epoca Contemporană',
            'Cultura și știința universală în Epoca Contemporană',
            'Cultura și știința universală în Epoca Contemporană',

            //LIMBA ROMANA
            'Limba română', 	
            'Limba română', 	
            'Limba română', 	
            'Limba română', 	
            'Limba română', 	
            'Personalitățile neamului',	
            'Personalitățile neamului',	
            'Comunitatea vorbitorilor de limbă română',	
            'Comunitatea vorbitorilor de limbă română',	
            'Cultura națională și europeană',	
            'Cultura națională și europeană',	
            'Elemente de fonetică şi ortografie',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Lexicul',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Morfologia',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Sintaxa',	
            'Cartea',	
            'Cartea',	
            'Cartea',	
            'Structura operii literare',	
            'Structura operii literare',	
            'Personaje principale și personaje secundare',	
            'Personaje principale și personaje secundare',	
            'Personaje principale și personaje secundare',	
            'Personaje principale și personaje secundare',	
            'Text narativ',	
            'Text narativ',	
            'Text narativ',	
            'Text narativ',	
            'Text narativ',	
            'Text narativ',	
            'Text narativ',	
            'Text narativ',	
            'Text liric',	
            'Text liric',	
            'Text dramatic',	
            'Elementele de versificație',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Figurile de stil',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Genuri și specii literare',	
            'Literatura populară și literatura cultă',	
            'Textul literar și nonliterar',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea reflexivă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea imaginativă',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Scrierea funcțională',	
            'Interese și preferințe de lectură', 	
            'Interese și preferințe de lectură', 	
            'Raftul de literature artistică în biblioteca personală', 	
            'Interconexiunea literaturii cu alte disciplini',	
            'Interconexiunea literaturii cu alte disciplini',	
            'Interconexiunea literaturii cu alte disciplini',	
            'Interconexiunea literaturii cu alte disciplini',	
            'Literatura în viața cotidiană', 	
            'Literatura în viața cotidiană', 	


        ];

        $subjects = [
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',
            'Istoria',

            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
            'Limba română',
 
        ];


        $themeId = Theme::firstWhere('name', $thems[$this->index])->id;

        $topic = $this->values[$this->index];

        $subjectId = Subject::firstWhere('name', $subjects[$this->index])->id;
        $studyLevelId = StudyLevel::firstWhere('name', 'Ciclu gimnazial')->id;

        $subjectStudyLevelId = SubjectStudyLevel::where('study_level_id', $studyLevelId) ->where('subject_id', $subjectId) ->first()->id;
        $learningProgramIstoriaId = LearningProgram::where('subject_study_level_id', $subjectStudyLevelId)
                                         ->where('year', 2022)
                                         ->first()->id;

        $themeLearningProgramIstoriaId = ThemeLearningProgram::where('learning_program_id', $learningProgramIstoriaId)
                                         ->where('theme_id', $themeId)
                                         ->first()->id;

        $this->orderNumber = isset($this->previousThemeId) && $themeId == $this->previousThemeId
        ? $this->orderNumber + 1
        : 1;

        $this->previousThemeId = $themeId;                                

        $this->index++;

        return [
            'name' => $topic['nume'],
            'path' => $topic['path'],            
            'order_number' => $this->orderNumber,
            'theme_learning_program_id'=> $themeLearningProgramIstoriaId,   
        ];
    }
}

