<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Theme;
use App\Models\StudyLevel;
use App\Models\Subject;
use App\Models\LearningProgram;
use App\Models\SubjectStudyLevel;
use App\Models\ThemeLearningProgram;

class TopicFactory extends Factory
{
    private $values = [
        //Thema Mulțimea numerelor naturale
        'Mulţimi.Operaţii cu mulţimi. Mulţimile: N,Z,Q,R',
        'Operaţii cu numere naturale',
        'Divizibilitate în N. Criteriile de divizibilitate cu 2, 3, 5, 9, 10',
        'Cel mai mare divizor comun al două numere naturale',
        'Cel mai mic multiplu comun al două numere naturale',

        //Thema Mulțimea numerelor întregi
        'Modulul numărului întreg', 
        'Operaţii cu numere întregi',

         //Thema Mulțimea numerelor raționale
        'Scrierea numerelor raţionale în diverse forme', 
        'Operaţii cu numere raţionale',
         
         //Thema Mulțimea numerelor reale
         'Rădăcina pătrată (radical), proprietăți',
         'Introducerea factorilor sub radical, scoaterea factorilor de sub radical', 
         'Compararea unor numere ce conțin radicali. Modulul numărului real',
         'Operații cu radicali. Raţionalizarea numitorului', 
         'Submulţimi ale mulţimii numerelor reale. Noţiune de număr iraţional',

        // MATEM CAPITOL 2 - Rapoarte şi proporţii
        //'Rapoarte. Proporţii. Proprietatea fundamentală a proporţiilor',
         'Proporții',
        'Proprietatea fundamentală a proporției. Aflarea unui termen necunoscut al proporției',
        // 'Mărimi direct proporţionale şi mărimi invers proporţionale',
        'Mărimi direct proporționale',
        'Mărimi invers proporționale',
        'Regula de trei simplă',
        //'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',
        'Aflarea raportului procentual',
        'Aflarea procentului dintr-un număr dat',
        'Aflarea unui număr când se cunoaște procentul din el',
         // 'Media aritmetică',
        'Media aritmetică',

        // MATEM CAPITOL 3 - Calcul algebric
        //'Operaţii cu numere reale reprezentate prin litere',
        'Expresii algebrice',
        'Adunarea, scăderea numerelor reale reprezentate prin litere',
        'Înmulțirea numerelor reale reprezentate prin litere',
        'Împărțirea numerelor reale reprezentate prin litere',
        'Ridicare la putere cu exponent natural un număr real reprezentat prin litere',
        // 'Formule de calcul prescurtat',
        'Formule de calcul prescurtat',
        // 'Metode de descompunere în factori',
        'Metoda factorului comun',
        'Aplicarea formulelor de calcul prescurtat',
        'Metoda grupării termenilor și scoaterii factorului comun',
         // 'Transformări identice ale expresiilor algebrice',
        'Definiții',
        'Modalităţi de demonstraţie a identităţilor',
        //  'Rapoarte (fracții) algebrice, DVA',
        'Domeniul valorilor admisibile (DVA) al unei fracţii algebrice.',
        'Operaţii aritmetice cu fracţii algebrice',
        // MATEM CAPITOL 4 - Funcţii 
        //  'Coordonatele punctului pe plan',
        'Sistemul cartezian de coordonate în plan. Axe',
        'Originea sistemului, cadrane, abscisă, ordonată',
        'Coordonatele punctului',
        // 'Noţiune de funcţie. Graficul funcţiei',
        'Domeniul de definiție, codomeniu',
        'Moduri de definire a funcției',
        'Graficul funcției',
        // 'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',
        'Funcția constantă. Reprezentarea grafică. Proprietăți',
        'Proporţionalitate inversă',
        'Funcția radical',
        //  'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi',
        'Cazuri particulare ale funcției de gradul II',
        'Graficul funcției de gradul II.',
        'Proprietățile funcției de gradul II',
        // MATEM CAPITOL 5 - Ecuaţii, inecuaţii, sisteme de ecuaţii, sisteme de inecuaţii 
        // 'Ecuaţii de gradul I cu o necunoscută',
        'Noțiunea de ecuație cu o necunoscută',
        'Ecuații de gradul I cu o necunoscută',
        'Ecuații reductibile la ecuația de gradul I cu o necunoscută',
        //  'Sisteme de ecuaţii de gradul I cu două necunoscute', 
        'Ecuații cu două necunoscute.Soluția. DVA',
        'Ecuații de gradul I cu două necunoscute',
        'Noțiune de sistem de 2 ecuații cu 2 necunoscute',
        'Sisteme de 2 ecuații de gradul I cu 2 necunoscute',
        'Metode de rezolvare a sistemelor de 2 ecuații de gradul I cu 2 necunoscute',
        //  'Inecuaţii de gradul I cu o necunoscută',
        'Inegalități numerice.',
        'Intervale de numere reale. Operații cu intervale de numere reale',
        'Noțiunea de inecuație cu o necunoscută',
        'Inecuații de gradul I cu 1 necunoscută',
        //  'Sisteme de inecuaţii de gradul I cu o necunoscută',
        'Sisteme de inecuații de gradul I cu 1 necunoscută',
        //  'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',
        'Formula de rezolvare',
        'Relații între soluții și coeficienți. Reciproca teoremei lui Viète',
        'Ecuații reductibile la ecuația de gradul II cu o necunoscută',
        //  'Inecuaţii de gradul II cu o necunoscută',
        'Inecuații de gradul II cu o necunoscută',
        'Metoda intervalelor',
        //  'Ecuaţii raţionale cu o necunoscută',
        'Ecuații raționale',

         // MATEM CAPITOL 6 - Geometrie   
         //  'Unități de măsură (lungime, timp, arie, volum)',
        'Unități de măsură pentru lungime',
        'Unități de măsură pentru suprafață',
        'Unități de măsură pentru volum',
        'Unități de măsură pentru capacitate',
        'Unități de măsură pentru masă',
        'Unități de măsură pentru timp',
         //  'Noțiuni geometrice fundamentale', 
        'Punct, dreaptă, plan, distanța dintre două puncte, măsura unghiului',
        'Puncte coliniare. Semidreaptă. Segment.',
        'Unghi. Definiție, clasificare. Măsura unghiului',
        'Poziţii relative a două drepte. Drepte paralele, perpendiculare',
        'Simetria față de un punct, simetria față de o dreaptă',
        //  'Triunghiuri',
        'Triunghi. Definiție, elemente, clasificarea triunghiurilor',
        'Triunghiuri congruente. Criteriile de congruență',
        'Triunghiuri asemenea. Teorema lui Thales',
        'Linii importante în triunghi: mediana, bisectoarea, înălțimea, mediatoarea',
        'Suma măsurilor unghiurilor unui triunghi. Teorema unghiului exterior',
        'Proprietățile triunghiului isoscel',
        'Proprietățile triunghiului echilateral',
        'Proprietățile triunghiului dreptunghic',
        'Teorema înălțimii. Teorema catetei. Teorema lui Pitagora',
        //  'Patrulatere. Poligoane.',
        'Noțiunea de poligon. Poligoane convexe. Elemente',
        'Noțiunea de patrulater. Elemente. Patrulatere convexe',
        'Paralelogramul. Elemente, proprietăți, criterii',
        'Dreptunghiul, elemente, proprietăți, criterii',
        'Rombul, elemente, proprietăți,criterii',
        'Pătratul, elemente, proprietăți,criterii',
        'Trapezul, elemente, clasificare,proprietăți. Linia mijlocie a trapezului',
        'Noțiunea de poligon regulat. Elemente. Triunghiul echilateral, pătratul',
        //  'Cercul. Discul', 
        'Cercul. Discul. Elemente',
        'Poziția relativă a unei drepte față de un cerc',
        'Unghi la centru. Unghi înscris în cerc. Arc de cerc',
        'Tangenta la cerc. Proprietăți',
        'Proprietatea coardelor egal depărtate de centrul cercului',
        //   'Arii', 
        'Noțiune de arie',
        'Aria pătratului, dreptunghiului',
        'Aria paralelogramului',
        'Aria rombului',
        'Aria triunghiului (A = 0,5 ah; formula lui Heron)',
        'Aria trapezului',
        'Aria triunghiului echilateral',
        'Lungimea cercului. Aria discului',
        //  'Poliedre',
        'Prisma și elementele ei, clasificarea prismelor',
        'Aria suprafețelor și volumul prismei drepte',
        'Piramida și elementele ei, clasificarea piramidelor',
        'Aria suprafețelor și volumul piramidei regulate (triunghiulare, patrulatere)',
        //  'Corpuri de rotație',
        'Noțiune de cilindru. Cilindrul circular drept și elementele lui',
        'Aria suprafețelor și volumul cilindrului circular drept',
        'Noțiune de con. Conul circular drept și elementele lui',
        'Aria suprafețelor și volumul conului circular drept',
        'Sfera și corpul sferic. Elemente',
        'Aria suprafeței sferice. Volumul corpului sferic',


        // Thema România în Primul Război Mondial
        'Opțiunile politice în perioada neutralității',
        'Mișcarea națională a românilor din Basarabia și teritoriile din stânga Nistrului',
        'Formarea Statului Național Unitar Român. Recunoașterea Marii Uniri de la 1918',
        'Conferinţa de Pace de la Paris. Sistemul de la Versailles'
    ];
    private $index = 0;

    public function definition(): array
    {
        $thems = [ 
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor naturale', 			
             'Mulțimea numerelor întregi', 			
             'Mulțimea numerelor întregi',  			
             'Mulțimea numerelor raționale',			
             'Mulțimea numerelor raționale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Mulțimea numerelor reale',			
             'Rapoarte. Proporţii. Proprietatea fundamentală a proporţiilor',			
             'Rapoarte. Proporţii. Proprietatea fundamentală a proporţiilor',			
             'Mărimi direct proporţionale şi mărimi invers proporţionale. Regula de trei simplă',			
             'Mărimi direct proporţionale şi mărimi invers proporţionale. Regula de trei simplă',			
             'Mărimi direct proporţionale şi mărimi invers proporţionale. Regula de trei simplă',			
             'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',			
             'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',			
             'Procente. Aflarea % dintr-un număr dat. Aflarea unui număr din %',			
             'Media aritmetică',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Operaţii cu numere reale reprezentate prin litere',			
             'Formule de calcul prescurtat',			
             'Metode de descompunere în factori',			
             'Metode de descompunere în factori',			
             'Metode de descompunere în factori',			
             'Transformări identice ale expresiilor algebrice',			
             'Transformări identice ale expresiilor algebrice',			
             'Rapoarte (fracții) algebrice, DVA',			
             'Rapoarte (fracții) algebrice, DVA',			
             'Coordonatele punctului pe plan',			
             'Coordonatele punctului pe plan',			
             'Coordonatele punctului pe plan',			
             'Noţiune de funcţie. Graficul funcţiei',			
             'Noţiune de funcţie. Graficul funcţiei',			
             'Noţiune de funcţie. Graficul funcţiei',			
             'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',			
             'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',			
             'Funcţia de gradul I. Reprezentarea grafică. Proprietăţi',			
             'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi', 			
             'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi', 			
             'Funcţia de gradul II. Reprezentarea grafică. Proprietăţi', 			
             'Ecuaţii de gradul I cu o necunoscută',			
             'Ecuaţii de gradul I cu o necunoscută',			
             'Ecuaţii de gradul I cu o necunoscută',			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Sisteme de ecuaţii de gradul I cu două necunoscute', 			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Inecuaţii de gradul I cu o necunoscută',			
             'Sisteme de inecuaţii de gradul I cu o necunoscută',			
             'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',			
             'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',			
             'Ecuaţii de gradul II cu o necunoscută. Relaţiile Viète',			
             'Inecuaţii de gradul II cu o necunoscută',			
             'Inecuaţii de gradul II cu o necunoscută',			
             'Ecuaţii raţionale cu o necunoscută',			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Unități de măsură (lungime, timp, arie, volum)', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Noțiuni geometrice fundamentale', 			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Triunghiuri',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Patrulatere. Poligoane.',			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Cercul. Discul', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Arii', 			
             'Poliedre',			
             'Poliedre',			
             'Poliedre',			
             'Poliedre',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'Corpuri de rotație',			
             'România în Primul Război Mondial',			
             'România în Primul Război Mondial',			
             'România în Primul Război Mondial',			
             'România în Primul Război Mondial'			
        ];

        $subjects = [
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica', 
             'Matematica', 
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Matematica',
             'Istoria',
             'Istoria',
             'Istoria',
             'Istoria'
        ];


        $themeId = Theme::firstWhere('name', $thems[$this->index])->id;

        $name = $this->values[$this->index];

        $subjectId = Subject::firstWhere('name', $subjects[$this->index])->id;
        $studyLevelId = StudyLevel::firstWhere('name', 'Ciclu gimnazial')->id;

        $subjectStudyLevelId = SubjectStudyLevel::where('study_level_id', $studyLevelId) ->where('subject_id', $subjectId) ->first()->id;
        $learningProgramIstoriaId = LearningProgram::where('subject_study_level_id', $subjectStudyLevelId)
                                         ->where('year', 2022)
                                         ->first()->id;

        $themeLearningProgramIstoriaId = ThemeLearningProgram::where('learning_program_id', $learningProgramIstoriaId)
                                         ->where('theme_id', $themeId)
                                         ->first()->id;

        $this->index++;

        return [
            'name' => $name,
            'theme_learning_program_id'=> $themeLearningProgramIstoriaId,   
        ];
    }
}

